name: Develop Android CI

on:
  push:
    branches: [develop]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Run Tests
        run: bash ./gradlew test --stacktrace
  build:
    name: Generate Builds
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APP_VERSION }}-apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Bundle
        run: bash ./gradlew bundleDebug --stacktrace

      - name: Upload Bundle
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APP_VERSION }}-bundle-debug
          path: app/build/outputs/bundle/debug/app-debug.aab
